SET STATISTICS TIME ON
--PURPOSE: Pause All PROJECTS
--Kyle K. - 03 / 17 / 2015

---MAKE A TEMP TABLE TO PULL TASK IDs FROM
CREATE TABLE #WF_PROJECT_STAGING (PROJECT_ID int NOT NULL,);

--POPULATE IT WITH TASK IDS
INSERT INTO #WF_PROJECT_STAGING
SELECT PROJECT_ID 
FROM PROJECTS
WHERE PROJECT_STATUS = 2



--See how many rows were dealing with
DECLARE @ROWS_REMAINING int;
SET @ROWS_REMAINING = (SELECT COUNT(*) FROM #WF_PROJECT_STAGING);

--Info Statement Only
PRINT @ROWS_REMAINING

--START MAIN LOOP
WHILE (@ROWS_REMAINING > 1)
BEGIN
	
	BEGIN TRAN
	UPDATE PROJECTS SET project_status = 3
	where PROJECT_ID IN(SELECT TOP 1000 PROJECT_ID from #WF_PROJECT_STAGING order by PROJECT_ID)

	DELETE FROM #WF_PROJECT_STAGING
	WHERE PROJECT_ID IN (SELECT TOP 1000 PROJECT_ID from #WF_PROJECT_STAGING order by PROJECT_ID)

	COMMIT

	SET @ROWS_REMAINING = @ROWS_REMAINING - 1000;
	

	--Info Statement Only
	PRINT @ROWS_REMAINING;

END;
--END MAIN LOOP

--Cleanup Table
DROP TABLE #WF_PROJECT_STAGING
GO

SET STATISTICS TIME OFF
